In [9]:
a=10
b=0
try:
    c=a/b
    print(c)
except ArithmeticError:
    print("Cannot perform divison")
finally:
    print("Successfull completion")

Cannot perform divison
Successfull completion


In [5]:
import numpy as np
ndarray = np.arange(0,15,dtype=object)
ndarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype=object)

In [7]:
array =  np.arange(0,15).reshape(5,3)

In [8]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
import numpy as np
a=[[[10,30,25],[25,35,45],[100,300,200]]]

In [17]:
a

[[[10, 30, 25], [25, 35, 45], [100, 300, 200]]]

In [14]:
import numpy as np
a=[[[10,30,25],[25,35,45],[100,300,200],[203,303,403],[204,304,404],[5,2,1]]]

In [15]:
a

[[[10, 30, 25],
  [25, 35, 45],
  [100, 300, 200],
  [203, 303, 403],
  [204, 304, 404],
  [5, 2, 1]]]

In [20]:
np.ndim(a)

3

In [21]:
len(a)

1

In [23]:
np.shape(a)

(1, 3, 3)

In [24]:
a[0]

[[10, 30, 25], [25, 35, 45], [100, 300, 200]]

In [25]:

a[0][0]

[10, 30, 25]

In [26]:
a[0][0][0]

10

In [27]:
a[0][0][0][0]

TypeError: 'int' object is not subscriptable

In [28]:
np.shape(a[0])

(3, 3)

In [29]:
np.shape(a[0][0])

(3,)

In [32]:
a

[[[10, 30, 25], [25, 35, 45], [100, 300, 200]]]

In [31]:
np.sum(a,axis=1)

array([[135, 365, 270]])