In [9]:
a=10
b=0
try:
    c=a/b
    print(c)
except ArithmeticError:
    print("Cannot perform divison")
finally:
    print("Successfull completion")

Cannot perform divison
Successfull completion


In [5]:
import numpy as np
ndarray = np.arange(0,15,dtype=object)
ndarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype=object)

In [7]:
array =  np.arange(0,15).reshape(5,3)

In [8]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
import numpy as np
a=[[[10,30,25],[25,35,45],[100,300,200]]]

In [17]:
a

[[[10, 30, 25], [25, 35, 45], [100, 300, 200]]]

In [35]:
import numpy as np
a=np.array([[[10,30,25],[25,35,45],[100,300,200],[203,303,403],[204,304,404],[5,2,1]]])

In [36]:
a

array([[[ 10,  30,  25],
        [ 25,  35,  45],
        [100, 300, 200],
        [203, 303, 403],
        [204, 304, 404],
        [  5,   2,   1]]])

In [39]:
a.ndim

3

In [41]:
a.shape

(1, 6, 3)

In [42]:
np.shape(a)

(1, 6, 3)

In [43]:
a[0]

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [44]:

a[0][0]

array([10, 30, 25])

In [45]:
a[0][0][0]

np.int64(10)

In [47]:
np.shape(a[0])

(6, 3)

In [48]:
np.shape(a[0][0])

(3,)

In [49]:
a

array([[[ 10,  30,  25],
        [ 25,  35,  45],
        [100, 300, 200],
        [203, 303, 403],
        [204, 304, 404],
        [  5,   2,   1]]])

In [50]:
np.sum(a,axis=1)

array([[ 547,  974, 1078]])

In [51]:
type(a)

numpy.ndarray

In [52]:
np.sum(a,axis=0)

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [55]:
a[0]

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [61]:
ary=a.reshape(3,2,3)
ary

array([[[ 10,  30,  25],
        [ 25,  35,  45]],

       [[100, 300, 200],
        [203, 303, 403]],

       [[204, 304, 404],
        [  5,   2,   1]]])

In [62]:
ary.shape

(3, 2, 3)

In [75]:
a=np.array([1,2,3,4,5,6,7,8,9,0],dtype=str,copy=True)

In [76]:
type(a)

numpy.ndarray

In [77]:
print(a)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '0']


In [89]:
a=np.array([[1,2],[2,4]], dtype=int, copy=True,order='F',subok=True,ndmin=3)

In [96]:
print(type(a))
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.flags)
print(a.data)

<class 'numpy.ndarray'>
3
4
8
32
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [97]:
print(help(np.put))

Help on _ArrayFunctionDispatcher in module numpy:

put(a, ind, v, mode='raise')
    Replaces specified elements of an array with given values.

    The indexing works on the flattened target array. `put` is roughly
    equivalent to:

    ::

        a.flat[ind] = v

    Parameters
    ----------
    a : ndarray
        Target array.
    ind : array_like
        Target indices, interpreted as integers.
    v : array_like
        Values to place in `a` at target indices. If `v` is shorter than
        `ind` it will be repeated as necessary.
    mode : {'raise', 'wrap', 'clip'}, optional
        Specifies how out-of-bounds indices will behave.

        * 'raise' -- raise an error (default)
        * 'wrap' -- wrap around
        * 'clip' -- clip to the range

        'clip' mode means that all indices that are too large are replaced
        by the index that addresses the last element along that axis. Note
        that this disables indexing with negative numbers. In 'raise' mode,
      

In [99]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [110]:
a=np.array([1,2,3,4,5,6,7,8,9,0,10,11,12,13],dtype=object)
print(a)

[1 2 3 4 5 6 7 8 9 0 10 11 12 13]


In [112]:
print(np.put(a,[10,11],["Manivel","King"]))

None


In [113]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 'Manivel', 'King', 12, 13],
      dtype=object)