In [3]:
a=10
b=0
try:
    c=a/b
    print(c)
except ArithmeticError:
    print("Cannot perform divison")
finally:
    print("Successfull completion")

Cannot perform divison
Successfull completion


In [4]:
import numpy as np
ndarray = np.arange(0,15,dtype=object)
ndarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype=object)

In [5]:
array =  np.arange(0,15).reshape(5,3)

In [6]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
import numpy as np
a=[[[10,30,25],[25,35,45],[100,300,200]]]

In [8]:
a

[[[10, 30, 25], [25, 35, 45], [100, 300, 200]]]

In [9]:
import numpy as np
a=np.array([[[10,30,25],[25,35,45],[100,300,200],[203,303,403],[204,304,404],[5,2,1]]])

In [10]:
a

array([[[ 10,  30,  25],
        [ 25,  35,  45],
        [100, 300, 200],
        [203, 303, 403],
        [204, 304, 404],
        [  5,   2,   1]]])

In [11]:
a.ndim

3

In [12]:
a.shape

(1, 6, 3)

In [13]:
np.shape(a)

(1, 6, 3)

In [14]:
a[0]

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [15]:

a[0][0]

array([10, 30, 25])

In [16]:
a[0][0][0]

np.int64(10)

In [17]:
np.shape(a[0])

(6, 3)

In [18]:
np.shape(a[0][0])

(3,)

In [19]:
a

array([[[ 10,  30,  25],
        [ 25,  35,  45],
        [100, 300, 200],
        [203, 303, 403],
        [204, 304, 404],
        [  5,   2,   1]]])

In [20]:
np.sum(a,axis=1)

array([[ 547,  974, 1078]])

In [21]:
type(a)

numpy.ndarray

In [22]:
np.sum(a,axis=0)

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [23]:
a[0]

array([[ 10,  30,  25],
       [ 25,  35,  45],
       [100, 300, 200],
       [203, 303, 403],
       [204, 304, 404],
       [  5,   2,   1]])

In [24]:
ary=a.reshape(3,2,3)
ary

array([[[ 10,  30,  25],
        [ 25,  35,  45]],

       [[100, 300, 200],
        [203, 303, 403]],

       [[204, 304, 404],
        [  5,   2,   1]]])

In [25]:
ary.shape

(3, 2, 3)

In [26]:
a=np.array([1,2,3,4,5,6,7,8,9,0],dtype=str,copy=True)

In [27]:
type(a)

numpy.ndarray

In [28]:
print(a)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '0']


In [29]:
a=np.array([[1,2],[2,4]], dtype=int, copy=True,order='F',subok=True,ndmin=3)

In [30]:
print(type(a))
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.flags)
print(a.data)

<class 'numpy.ndarray'>
3
4
8
32
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [31]:
print(help(np.put))

Help on _ArrayFunctionDispatcher in module numpy:

put(a, ind, v, mode='raise')
    Replaces specified elements of an array with given values.

    The indexing works on the flattened target array. `put` is roughly
    equivalent to:

    ::

        a.flat[ind] = v

    Parameters
    ----------
    a : ndarray
        Target array.
    ind : array_like
        Target indices, interpreted as integers.
    v : array_like
        Values to place in `a` at target indices. If `v` is shorter than
        `ind` it will be repeated as necessary.
    mode : {'raise', 'wrap', 'clip'}, optional
        Specifies how out-of-bounds indices will behave.

        * 'raise' -- raise an error (default)
        * 'wrap' -- wrap around
        * 'clip' -- clip to the range

        'clip' mode means that all indices that are too large are replaced
        by the index that addresses the last element along that axis. Note
        that this disables indexing with negative numbers. In 'raise' mode,
      

In [32]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [33]:
a=np.array([1,2,3,4,5,6,7,8,9,0,10,11,12,13],dtype=object)
print(a)

[1 2 3 4 5 6 7 8 9 0 10 11 12 13]


In [34]:
print(np.put(a,[10,11],["Manivel","King"]))

None


In [35]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 'Manivel', 'King', 12, 13],
      dtype=object)

In [36]:
dt = np.dtype([('age',np.int8),('sex','U20')])

In [37]:
b=np.array((10,"Manivel Rengasamy"),dtype=dt)

In [38]:
print(b)

(10, 'Manivel Rengasamy')


In [39]:
type(dt)

numpy.dtypes.VoidDType

In [40]:
import numpy as np
dt = np.dtype([("U20", np.int8)])

In [41]:
import numpy as np 
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [42]:
import inspect
print(inspect.isfunction(a.itemsize))

False


In [65]:
a = np.empty(shape=(400,3),dtype=float,order='C') 
print(a)

[[6.95282267e-310 9.13979358e-312 6.95282267e-310]
 [6.95282267e-310 6.95282267e-310 6.95282267e-310]
 [6.95282267e-310 9.13979358e-312 6.95282262e-310]
 ...
 [9.13777206e-312 9.13777206e-312 9.13979404e-312]
 [6.95282267e-310 6.95282267e-310 6.95282267e-310]
 [6.95282267e-310 9.13979404e-312 6.95282267e-310]]


In [66]:
import pandas as pd

In [67]:
A=pd.DataFrame(a)

In [68]:
A

0              1              2
0    6.952823e-310  9.139794e-312  6.952823e-310
1    6.952823e-310  6.952823e-310  6.952823e-310
2    6.952823e-310  9.139794e-312  6.952823e-310
3    6.952823e-310  6.952823e-310  6.952823e-310
4    9.139794e-312  9.139794e-312  6.952823e-310
..             ...            ...            ...
395  6.952823e-310  6.952823e-310  6.952823e-310
396  6.952823e-310  6.952823e-310  9.137772e-312
397  9.137772e-312  9.137772e-312  9.139794e-312
398  6.952823e-310  6.952823e-310  6.952823e-310
399  6.952823e-310  9.139794e-312  6.952823e-310

[400 rows x 3 columns]

In [69]:
A.columns=["A","B","C"]

In [56]:
A

A              B              C
0    9.881313e-324  9.314728e-315   0.000000e+00
1    1.684764e-321            NaN  5.562748e-309
2    1.112552e-308  4.450185e-307  5.340473e-307
3    6.230516e-307            NaN  6.452765e-307
4    5.286061e-303  7.120359e-307            NaN
..             ...            ...            ...
395  9.137841e-312  6.952823e-310  9.139794e-312
396  9.139794e-312  9.137628e-312  6.952823e-310
397  9.139794e-312  9.137501e-312  9.137809e-312
398  6.952823e-310  9.139794e-312  9.137842e-312
399  9.137811e-312  9.139794e-312  9.137628e-312

[400 rows x 3 columns]

In [82]:
a=np.ones(shape=(10,3),order=None)

In [83]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [98]:
s=b"Manivel is the good and bad boy. He is willing to travel anywhere in the world without knowing nothing"
a=np.frombuffer(s,dtype="S1",offset=10,count=13)

In [99]:
a

array([b' ', b't', b'h', b'e', b' ', b'g', b'o', b'o', b'd', b' ', b'a',
       b'n', b'd'], dtype='|S1')

In [100]:
a=[1,2,3,4]
b=np.asarray(a)
print(b)

[1 2 3 4]


In [102]:
print(type(a))
type(b)

<class 'list'>


numpy.ndarray

In [103]:
b=np.array(a)

In [104]:
b

array([1, 2, 3, 4])

In [106]:
import numpy as np
a=[1,2,np.inf, np,nan]

NameError: name 'nan' is not defined

In [110]:
a=np.full((2,2),np.nan)

In [111]:
a

array([[nan, nan],
       [nan, nan]])

In [113]:
x = np.arange(6, dtype=int) 
y= np.full_like(x, 0.454545, dtype=np.double) 
print(y)

[0.454545 0.454545 0.454545 0.454545 0.454545 0.454545]


In [114]:
y.size

6

In [127]:
a=np.random.randn(1,10)
a

array([[-0.73525417,  0.85101575,  0.91561348, -1.28371392,  0.6246094 ,
         1.17514166, -0.8417479 ,  0.28268224, -0.41612681, -0.53692515]])

In [125]:

a

array([5, 6, 9], dtype=int32)

In [130]:

a=np.arange(10).reshape(2,5)
b=np.random.rand(5,2)
c=np.matmul(a,b)
print(c)

[[ 3.84147858  4.7884062 ]
 [10.40425989 18.77918065]]


In [137]:
c=np.linalg.det(a)
c

LinAlgError: Last 2 dimensions of the array must be square

In [139]:
a=np.array([[1,2,3,],[1,3,4],[1,5,9]])

In [140]:

a

array([[1, 2, 3],
       [1, 3, 4],
       [1, 5, 9]])

In [143]:
print(np.min(a,axis=1))

[1 1 1]


In [144]:
print(np.max(a,axis=0))

[1 5 9]


In [146]:
import numpy as np 
a = np.array([4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) 
for i in enumerate (a): 
    print(i)

(0, np.int64(4))
(1, np.int64(5))
(2, np.int64(6))
(3, np.int64(7))
(4, np.int64(8))
(5, np.int64(9))
(6, np.int64(10))
(7, np.int64(11))
(8, np.int64(12))
(9, np.int64(13))
(10, np.int64(14))


In [160]:
from numpy import genfromtxt
dt = genfromtxt("election_data.csv",delimiter=',',skip_footer=True,skip_header=30,filling_values={0.100,0.200})

TypeError: float() argument must be a string or a real number, not 'set'

In [161]:
dt

array([[  nan, 39.51],
       [  nan, 39.41],
       [  nan, 39.06],
       [  nan, 38.27],
       [  nan, 37.4 ],
       [  nan, 37.11],
       [  nan, 35.09],
       [  nan, 33.93]])

In [162]:

import numpy as np 
a = np.arange(10) 
print(a) 
s= slice(4)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]


In [163]:
a=np.random.randint(low=1,high=20,size=20)

In [164]:
a

array([ 2,  2, 15,  8, 18, 11,  3,  1,  9, 18,  6, 16,  5, 12, 13,  7, 15,
       11, 15, 15], dtype=int32)

In [168]:
import numpy as np 
a = np.array([ [1,2,3], [4,5,6]]) 
print(a) 
print("# Now we will slice ALL (:) items from column 1 onwards ") 
print(a[1:])

[[1 2 3]
 [4 5 6]]
# Now we will slice ALL (:) items from column 1 onwards 
[[4 5 6]]


In [170]:
print(a[...,0:])

[[1 2 3]
 [4 5 6]]


In [172]:
x

array([[   0,    1,    2],
       [ 300,  400,  500],
       [   6,    7,    8],
       [ 900, 1000, 1100]])

In [182]:
x=np.array([ [0,1,2], [300,400,500], [6,7,8], [900, 1000, 1100]])

rows = x [[[0,0], [3,2]], [[0,1],[1,1]]]
print(rows)
rows[(rows>1)]

[[   0    1]
 [1000    7]]


array([1000,    7])